spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oms_project
    username: root
    password: 123456
  data:
    redis:
      host: localhost
      port: 6379
      maxIdle: 300
      maxActive: 600
      maxWait: 1000